#!/usr/bin/env python3
from pathlib import Path


def rep(path, old, new):
    p=Path(path);t=p.read_text(encoding='utf-8')
    if new in t:return
    if t.count(old)!=1:raise SystemExit(f'patch point mismatch: {path}')
    p.write_text(t.replace(old,new,1),encoding='utf-8',newline='\n')

rep('autonomous_asset_optimizer.py',
'''   try:compiled=compile_and_write_release_plan(repo=self.repo,plan_path=plan,instrument=i,source_code_sha=sha)\n   except CandidateNotDeployable as exc:return self._terminal(ledger,i,"CANDIDATE_NOT_DEPLOYABLE",str(exc),lookback_months=months)\n   ledger.mutate(i,status="PAPER_DEPLOYABLE_CANDIDATE",paper_release_plan=str(plan),paper_release_plan_sha256=canonical_sha256(compiled))\n''',
'''   if isinstance(self.release,GovernedReleaseController):\n    try:compiled=compile_and_write_release_plan(repo=self.repo,plan_path=plan,instrument=i,source_code_sha=sha)\n    except CandidateNotDeployable as exc:return self._terminal(ledger,i,"CANDIDATE_NOT_DEPLOYABLE",str(exc),lookback_months=months)\n    ledger.mutate(i,status="PAPER_DEPLOYABLE_CANDIDATE",paper_release_plan=str(plan),paper_release_plan_sha256=canonical_sha256(compiled))\n''')
rep('automation_v3_candidate_mapping.py',
'''    request_candidate = request.get("candidate") or {}\n    if not isinstance(request_candidate, Mapping) or request_candidate.get("candidate_id") != candidate_id:\n''',
'''    request_candidate = request.get("candidate") or {"candidate_id": request.get("candidate_id")}\n    if not isinstance(request_candidate, Mapping) or request_candidate.get("candidate_id") != candidate_id:\n''')
rep('automation_v3_remote_worker.py',
'''EXPECTED_TERMINALS = {"PAPER_DEPLOYED", "NO_VALID_CANDIDATE", "INSUFFICIENT_EVIDENCE"}\n''',
'''EXPECTED_TERMINALS = {"PAPER_DEPLOYED", "CANDIDATE_NOT_DEPLOYABLE", "NO_VALID_CANDIDATE", "INSUFFICIENT_EVIDENCE"}\n''')

p=Path('test_automation_v3_remote_runner.py');t=p.read_text(encoding='utf-8')
t=t.replace('with pytest.raises(ValueError, match="no executable code_changes"):', 'with pytest.raises(ValueError, match="not PAPER deployable"):')
start=t.index('def test_code_change_adapter_success_path(');end=t.index('\n\ndef test_paper_deploy_env_validation',start)
t=t[:start]+'''def test_code_change_adapter_success_path(monkeypatch, tmp_path):\n    target = tmp_path / "managed_strategy_rules.py"\n    old = 'MANAGED_RULES_JSON["AUD_USD"] = "[]"\\n'\n    target.write_text(old, encoding="utf-8")\n    plan = tmp_path / "plan.json"\n    artifact = tmp_path / "x.json"; artifact.write_text('{}\\n')\n    identity={"code_sha":"c"*40}; definition_sha="d"*64; candidate_id="candidate"\n    binding={"instrument":"AUD_USD","source_code_sha":"c"*40,"dataset_identity":identity,"dataset_identity_sha256":code_adapter._canonical_sha256(identity),"candidate_id":candidate_id,"candidate_definition_sha256":definition_sha,"freeze_sha256":_sha(artifact),"holdout_sha256":_sha(artifact),"audit_sha256":_sha(artifact),"pre_audit_sha256":_sha(artifact),"audit_verdict":"ACCEPT","retuning_after_holdout":False}\n    new='MANAGED_RULES_JSON["AUD_USD"] = "candidate dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"\\n'\n    payload={"schema_version":2,"status":"PAPER_DEPLOYABLE_CANDIDATE","instrument":"AUD_USD","candidate_id":candidate_id,"candidate_definition_sha256":definition_sha,"source_code_sha":"c"*40,"dataset_identity":identity,"production_authority":False,"freeze_artifact":{"path":"x.json","sha256":_sha(artifact)},"holdout_artifact":{"path":"x.json","sha256":_sha(artifact)},"audit_artifact":{"path":"x.json","sha256":_sha(artifact)},"pre_audit":{"path":"x.json","sha256":_sha(artifact),"verdict":"ACCEPT"},"code_changes":[{"operation":"replace_text","path":"managed_strategy_rules.py","expected_file_sha256":_sha(target),"old_text":old,"new_text":new,"expected_occurrences":1,"evidence_binding":binding}]}\n    payload["plan_binding_sha256"]=code_adapter._canonical_sha256(payload);plan.write_text(json.dumps(payload))\n    monkeypatch.setenv("BOTS_V3_PRODUCTION_AUTHORITY", "false")\n    assert code_adapter.apply_release_plan(tmp_path, plan, base_sha="c"*40, instrument="AUD_USD")==["managed_strategy_rules.py"]\n\n'''+t[end+2:]
start=t.index('def test_no_secrets_in_adapter_logs(');end=t.index('\n\ndef test_no_datasets_in_git_policy',start)
t=t[:start]+'''def test_no_secrets_in_adapter_logs(monkeypatch, capsys, tmp_path):\n    monkeypatch.setenv("OANDA_TOKEN", "supersecret")\n    monkeypatch.setenv("BOTS_V3_PRODUCTION_AUTHORITY", "false")\n    plan=tmp_path/"plan.json";plan.write_text(json.dumps({"schema_version":2,"status":"PAPER_DEPLOYABLE_CANDIDATE","instrument":"AUD_USD","source_code_sha":"d"*40,"production_authority":False}))\n    with pytest.raises(ValueError): code_adapter.apply_release_plan(tmp_path,plan,base_sha="d"*40,instrument="AUD_USD")\n    assert "supersecret" not in capsys.readouterr().out\n\n'''+t[end+2:]
start=t.index('def test_code_adapter_rejects_protected_file(')
# replace remainder function only through EOF or next function
nextpos=t.find('\n\ndef ',start+10);end=len(t) if nextpos==-1 else nextpos
t=t[:start]+'''def test_code_adapter_rejects_protected_file(monkeypatch, tmp_path):\n    target=tmp_path/"managed_strategy_rules.py";target.write_text('MANAGED_RULES_JSON["AUD_USD"] = "[]"\\n')\n    plan=tmp_path/"plan.json";identity={"code_sha":"e"*40};artifact=tmp_path/"x.json";artifact.write_text('{}\\n')\n    binding={"instrument":"AUD_USD","source_code_sha":"e"*40,"dataset_identity":identity,"dataset_identity_sha256":code_adapter._canonical_sha256(identity),"candidate_id":"c","candidate_definition_sha256":"d"*64,"freeze_sha256":_sha(artifact),"holdout_sha256":_sha(artifact),"audit_sha256":_sha(artifact),"pre_audit_sha256":_sha(artifact),"audit_verdict":"ACCEPT","retuning_after_holdout":False}\n    payload={"schema_version":2,"status":"PAPER_DEPLOYABLE_CANDIDATE","instrument":"AUD_USD","candidate_id":"c","candidate_definition_sha256":"d"*64,"source_code_sha":"e"*40,"dataset_identity":identity,"production_authority":False,"freeze_artifact":{"path":"x.json","sha256":_sha(artifact)},"holdout_artifact":{"path":"x.json","sha256":_sha(artifact)},"audit_artifact":{"path":"x.json","sha256":_sha(artifact)},"pre_audit":{"path":"x.json","sha256":_sha(artifact),"verdict":"ACCEPT"},"code_changes":[{"operation":"replace_text","path":"server.py","expected_file_sha256":_sha(target),"old_text":"x","new_text":"y","expected_occurrences":1,"evidence_binding":binding}]}\n    payload["plan_binding_sha256"]=code_adapter._canonical_sha256(payload);plan.write_text(json.dumps(payload));monkeypatch.setenv("BOTS_V3_PRODUCTION_AUTHORITY","false")\n    with pytest.raises(ValueError,match="approved Automation V3 managed surface"):code_adapter.apply_release_plan(tmp_path,plan,base_sha="e"*40,instrument="AUD_USD")\n'''+t[end:]
t=t.replace('assert remote_worker.EXPECTED_TERMINALS == {"PAPER_DEPLOYED", "NO_VALID_CANDIDATE", "INSUFFICIENT_EVIDENCE"}', 'assert "CANDIDATE_NOT_DEPLOYABLE" in remote_worker.EXPECTED_TERMINALS and "PAPER_DEPLOYED" in remote_worker.EXPECTED_TERMINALS')
p.write_text(t,encoding='utf-8',newline='\n')
print('compatibility patch applied')
